# Generated by Django 5.2.8 on 2025-12-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipationTache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CHEF', "Chef d'équipe"), ('MEMBRE', 'Membre')], default='MEMBRE', max_length=10, verbose_name='Rôle')),
                ('heures_travaillees', models.FloatField(default=0.0, verbose_name='Heures travaillées')),
                ('realisation', models.TextField(blank=True, verbose_name='Réalisation')),
            ],
            options={
                'verbose_name': 'Participation tâche',
                'verbose_name_plural': 'Participations tâches',
            },
        ),
        migrations.CreateModel(
            name='RatioProductivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_objet', models.CharField(help_text='Nom de la classe (Arbre, Gazon, Palmier, etc.)', max_length=50, verbose_name="Type d'objet")),
                ('unite_mesure', models.CharField(choices=[('m2', 'Mètres carrés'), ('ml', 'Mètres linéaires'), ('unite', 'Unité')], default='unite', max_length=10, verbose_name='Unité de mesure')),
                ('ratio', models.FloatField(help_text="Nombre d'unités traitables par heure", verbose_name='Ratio (unités/heure)')),
                ('description', models.TextField(blank=True, verbose_name='Description/Notes')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Ratio de productivité',
                'verbose_name_plural': 'Ratios de productivité',
                'ordering': ['id_type_tache', 'type_objet'],
            },
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut_planifiee', models.DateTimeField(verbose_name='Date début planifiée')),
                ('date_fin_planifiee', models.DateTimeField(verbose_name='Date fin planifiée')),
                ('date_echeance', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('priorite', models.IntegerField(choices=[(1, 'Priorité 1 (Très basse)'), (2, 'Priorité 2 (Basse)'), (3, 'Priorité 3 (Moyenne)'), (4, 'Priorité 4 (Haute)'), (5, 'Priorité 5 (Urgent)')], default=3, verbose_name='Priorité')),
                ('commentaires', models.TextField(blank=True, verbose_name='Commentaires')),
                ('date_affectation', models.DateField(blank=True, null=True, verbose_name="Date d'affectation")),
                ('date_debut_reelle', models.DateTimeField(blank=True, null=True, verbose_name='Date début réelle')),
                ('date_fin_reelle', models.DateTimeField(blank=True, null=True, verbose_name='Date fin réelle')),
                ('duree_reelle_minutes', models.IntegerField(blank=True, null=True, verbose_name='Durée réelle (minutes)')),
                ('charge_estimee_heures', models.FloatField(blank=True, help_text='Calculée automatiquement ou saisie manuellement', null=True, verbose_name='Charge estimée (heures)')),
                ('charge_manuelle', models.BooleanField(default=False, help_text='Si True, la charge ne sera pas recalculée automatiquement', verbose_name='Charge manuelle')),
                ('description_travaux', models.TextField(blank=True, verbose_name='Description des travaux')),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('NON_DEBUTEE', 'Non débutée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='PLANIFIEE', max_length=20, verbose_name='Statut')),
                ('note_qualite', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Note qualité (1-5)')),
                ('etat_validation', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=20, verbose_name='État de validation')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('commentaire_validation', models.TextField(blank=True, verbose_name='Commentaire de validation')),
                ('parametres_recurrence', models.JSONField(blank=True, null=True, verbose_name='Paramètres récurrence')),
                ('notifiee', models.BooleanField(default=False, verbose_name='Notifiée')),
                ('confirmee', models.BooleanField(default=False, verbose_name='Confirmée')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
                'ordering': ['date_debut_planifiee'],
            },
        ),
        migrations.CreateModel(
            name='TypeTache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tache', models.CharField(max_length=100, unique=True, verbose_name='Nom de la tâche')),
                ('symbole', models.CharField(blank=True, max_length=50, verbose_name='Symbole')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('productivite_theorique', models.FloatField(blank=True, null=True, verbose_name='Productivité théorique')),
                ('unite_productivite', models.CharField(blank=True, choices=[('m2', 'Mètres carrés (m²)'), ('ml', 'Mètres linéaires (ml)'), ('unite', 'Unités'), ('cuvettes', 'Cuvettes'), ('arbres', 'Arbres')], default='m2', max_length=20, verbose_name='Unité de productivité')),
            ],
            options={
                'verbose_name': 'Type de tâche',
                'verbose_name_plural': 'Types de tâches',
                'ordering': ['nom_tache'],
            },
        ),
    ]
