# Generated by Django 5.2.8 on 2025-12-14 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('api_users', '0003_alter_equipe_chef_equipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tache', models.CharField(max_length=100, unique=True, verbose_name='Nom de la tâche')),
                ('symbole', models.CharField(blank=True, max_length=50, verbose_name='Symbole')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('productivite_theorique', models.FloatField(blank=True, null=True, verbose_name='Productivité théorique')),
            ],
            options={
                'verbose_name': 'Type de tâche',
                'verbose_name_plural': 'Types de tâches',
                'ordering': ['nom_tache'],
            },
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut_planifiee', models.DateTimeField(verbose_name='Date début planifiée')),
                ('date_fin_planifiee', models.DateTimeField(verbose_name='Date fin planifiée')),
                ('date_echeance', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('priorite', models.IntegerField(choices=[(1, 'Priorité 1 (Très basse)'), (2, 'Priorité 2 (Basse)'), (3, 'Priorité 3 (Moyenne)'), (4, 'Priorité 4 (Haute)'), (5, 'Priorité 5 (Urgent)')], default=3, verbose_name='Priorité')),
                ('commentaires', models.TextField(blank=True, verbose_name='Commentaires')),
                ('date_affectation', models.DateField(blank=True, null=True, verbose_name="Date d'affectation")),
                ('date_debut_reelle', models.DateTimeField(blank=True, null=True, verbose_name='Date début réelle')),
                ('date_fin_reelle', models.DateTimeField(blank=True, null=True, verbose_name='Date fin réelle')),
                ('duree_reelle_minutes', models.IntegerField(blank=True, null=True, verbose_name='Durée réelle (minutes)')),
                ('description_travaux', models.TextField(blank=True, verbose_name='Description des travaux')),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('NON_DEBUTEE', 'Non débutée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='PLANIFIEE', max_length=20, verbose_name='Statut')),
                ('note_qualite', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Note qualité (1-5)')),
                ('parametres_recurrence', models.JSONField(blank=True, null=True, verbose_name='Paramètres récurrence')),
                ('notifiee', models.BooleanField(default=False, verbose_name='Notifiée')),
                ('confirmee', models.BooleanField(default=False, verbose_name='Confirmée')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='api_users.client', verbose_name='Client')),
                ('id_equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches', to='api_users.equipe', verbose_name='Équipe')),
                ('id_recurrence_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='api_planification.tache', verbose_name='Tâche mère')),
                ('objets', models.ManyToManyField(blank=True, related_name='taches', to='api.objet', verbose_name='Objets inventaire')),
                ('id_type_tache', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taches', to='api_planification.typetache', verbose_name='Type de tâche')),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
                'ordering': ['date_debut_planifiee'],
            },
        ),
        migrations.CreateModel(
            name='ParticipationTache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CHEF', "Chef d'équipe"), ('MEMBRE', 'Membre')], default='MEMBRE', max_length=10, verbose_name='Rôle')),
                ('heures_travaillees', models.FloatField(default=0.0, verbose_name='Heures travaillées')),
                ('realisation', models.TextField(blank=True, verbose_name='Réalisation')),
                ('id_operateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations_tache', to='api_users.operateur')),
                ('id_tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='api_planification.tache')),
            ],
            options={
                'verbose_name': 'Participation tâche',
                'verbose_name_plural': 'Participations tâches',
                'unique_together': {('id_tache', 'id_operateur')},
            },
        ),
    ]
