# Generated by Django 5.2.8 on 2025-12-26 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_initial'),
        ('api_planification', '0001_initial'),
        ('api_reclamations', '0001_initial'),
        ('api_users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participationtache',
            name='id_operateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations_tache', to='api_users.operateur'),
        ),
        migrations.AddField(
            model_name='tache',
            name='equipes',
            field=models.ManyToManyField(blank=True, related_name='taches', to='api_users.equipe', verbose_name='Équipes assignées'),
        ),
        migrations.AddField(
            model_name='tache',
            name='id_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches', to='api_users.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='tache',
            name='id_equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_legacy', to='api_users.equipe', verbose_name='Équipe (legacy)'),
        ),
        migrations.AddField(
            model_name='tache',
            name='id_recurrence_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='api_planification.tache', verbose_name='Tâche mère'),
        ),
        migrations.AddField(
            model_name='tache',
            name='objets',
            field=models.ManyToManyField(blank=True, related_name='taches', to='api.objet', verbose_name='Objets inventaire'),
        ),
        migrations.AddField(
            model_name='tache',
            name='reclamation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_correctives', to='api_reclamations.reclamation', verbose_name='Réclamation liée'),
        ),
        migrations.AddField(
            model_name='tache',
            name='validee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validée par'),
        ),
        migrations.AddField(
            model_name='participationtache',
            name='id_tache',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='api_planification.tache'),
        ),
        migrations.AddField(
            model_name='tache',
            name='id_type_tache',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taches', to='api_planification.typetache', verbose_name='Type de tâche'),
        ),
        migrations.AddField(
            model_name='ratioproductivite',
            name='id_type_tache',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratios_productivite', to='api_planification.typetache', verbose_name='Type de tâche'),
        ),
        migrations.AlterUniqueTogether(
            name='participationtache',
            unique_together={('id_tache', 'id_operateur')},
        ),
        migrations.AlterUniqueTogether(
            name='ratioproductivite',
            unique_together={('id_type_tache', 'type_objet')},
        ),
    ]
