# Generated by Django 5.2.8 on 2025-12-15 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_planification', '0001_initial'),
        ('api_users', '0003_alter_equipe_chef_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='id_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches', to='api_users.client', verbose_name='Client'),
        ),
    ]
