# Generated by Django 5.2.8 on 2025-12-31 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_planification', '0002_initial'),
        ('api_users', '0004_add_structure_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='id_structure_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches', to='api_users.structureclient', verbose_name='Structure cliente'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='id_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_legacy', to='api_users.client', verbose_name='[LEGACY] Client'),
        ),
    ]
