# Generated by Django 5.2.8 on 2025-12-17 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_planification', '0003_tache_reclamation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='charge_estimee_heures',
            field=models.FloatField(blank=True, help_text='Calculée automatiquement à partir des objets liés et ratios de productivité', null=True, verbose_name='Charge estimée (heures)'),
        ),
        migrations.CreateModel(
            name='RatioProductivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_objet', models.CharField(help_text='Nom de la classe (Arbre, Gazon, Palmier, etc.)', max_length=50, verbose_name="Type d'objet")),
                ('unite_mesure', models.CharField(choices=[('m2', 'Mètres carrés'), ('ml', 'Mètres linéaires'), ('unite', 'Unité')], default='unite', max_length=10, verbose_name='Unité de mesure')),
                ('ratio', models.FloatField(help_text="Nombre d'unités traitables par heure", verbose_name='Ratio (unités/heure)')),
                ('description', models.TextField(blank=True, verbose_name='Description/Notes')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('id_type_tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratios_productivite', to='api_planification.typetache', verbose_name='Type de tâche')),
            ],
            options={
                'verbose_name': 'Ratio de productivité',
                'verbose_name_plural': 'Ratios de productivité',
                'ordering': ['id_type_tache', 'type_objet'],
                'unique_together': {('id_type_tache', 'type_objet')},
            },
        ),
    ]
