# Generated by Django 5.2.8 on 2025-12-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_planification', '0004_ratioproductivite_charge_estimee'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='charge_manuelle',
            field=models.BooleanField(default=False, help_text='Si True, la charge ne sera pas recalculée automatiquement', verbose_name='Charge manuelle'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='charge_estimee_heures',
            field=models.FloatField(blank=True, help_text='Calculée automatiquement ou saisie manuellement', null=True, verbose_name='Charge estimée (heures)'),
        ),
    ]
