# Generated by Django 5.2.8 on 2026-01-10 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_planification', '0004_populate_structure_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Jour de travail', verbose_name='Date')),
                ('heures_planifiees', models.FloatField(help_text="Nombre d'heures prévues ce jour", verbose_name='Heures planifiées')),
                ('heures_reelles', models.FloatField(blank=True, help_text='Heures réellement travaillées (rempli après exécution)', null=True, verbose_name='Heures réelles')),
                ('commentaire', models.TextField(blank=True, help_text='Notes pour ce jour (équipe réduite, météo, etc.)', verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions_charge', to='api_planification.tache', verbose_name='Tâche')),
            ],
            options={
                'verbose_name': 'Distribution de charge',
                'verbose_name_plural': 'Distributions de charge',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['tache', 'date'], name='api_planifi_tache_i_117e0a_idx')],
                'unique_together': {('tache', 'date')},
            },
        ),
    ]
