# Generated by Django 5.2.8 on 2025-12-17 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_planification', '0005_charge_manuelle'),
        ('api_users', '0003_alter_equipe_chef_equipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='equipes',
            field=models.ManyToManyField(blank=True, related_name='taches', to='api_users.equipe', verbose_name='Équipes assignées'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='id_equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_legacy', to='api_users.equipe', verbose_name='Équipe (legacy)'),
        ),
    ]
