# Generated by Django 5.2.8 on 2026-01-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_planification', '0006_refactor_tache_distributions'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributioncharge',
            name='status',
            field=models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('TERMINEE', 'Terminée')], default='PLANIFIEE', help_text='État de la distribution de charge', max_length=20, verbose_name='Statut'),
        ),
    ]
