# Generated by Django 5.2.8 on 2025-12-19 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_planification', '0007_migrate_equipe_to_equipes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='commentaire_validation',
            field=models.TextField(blank=True, verbose_name='Commentaire de validation'),
        ),
        migrations.AddField(
            model_name='tache',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AddField(
            model_name='tache',
            name='etat_validation',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=20, verbose_name='État de validation'),
        ),
        migrations.AddField(
            model_name='tache',
            name='validee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validée par'),
        ),
    ]
