# Generated by Django 5.2.8 on 2026-01-12 10:38

from django.db import migrations, models


def migrate_status_values(apps, schema_editor):
    """
    Migrer les anciennes valeurs de statut vers les nouvelles:
    - PLANIFIEE -> NON_REALISEE
    - TERMINEE -> REALISEE
    """
    DistributionCharge = apps.get_model('api_planification', 'DistributionCharge')

    # Mettre à jour PLANIFIEE -> NON_REALISEE
    DistributionCharge.objects.filter(status='PLANIFIEE').update(status='NON_REALISEE')

    # Mettre à jour TERMINEE -> REALISEE
    DistributionCharge.objects.filter(status='TERMINEE').update(status='REALISEE')


def reverse_migrate_status_values(apps, schema_editor):
    """
    Migration inverse (rollback):
    - NON_REALISEE -> PLANIFIEE
    - REALISEE -> TERMINEE
    """
    DistributionCharge = apps.get_model('api_planification', 'DistributionCharge')

    # Rollback NON_REALISEE -> PLANIFIEE
    DistributionCharge.objects.filter(status='NON_REALISEE').update(status='PLANIFIEE')

    # Rollback REALISEE -> TERMINEE
    DistributionCharge.objects.filter(status='REALISEE').update(status='TERMINEE')


class Migration(migrations.Migration):

    dependencies = [
        ('api_planification', '0007_add_status_to_distribution_charge'),
    ]

    operations = [
        # Étape 1: Migrer les données existantes
        migrations.RunPython(migrate_status_values, reverse_migrate_status_values),

        # Étape 2: Modifier le champ avec les nouveaux choices
        migrations.AlterField(
            model_name='distributioncharge',
            name='status',
            field=models.CharField(choices=[('NON_REALISEE', 'Non Réalisée'), ('REALISEE', 'Réalisée')], default='NON_REALISEE', help_text='État de la distribution de charge', max_length=20, verbose_name='Statut'),
        ),
    ]
