# Generated by Django 5.2.8 on 2026-01-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_planification', '0008_update_distribution_status_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='id_recurrence_parent',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='parametres_recurrence',
        ),
        migrations.AddField(
            model_name='distributioncharge',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True, unique=True, verbose_name='Référence'),
        ),
        migrations.AddField(
            model_name='tache',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='Référence technique'),
        ),
    ]
