# Generated by Django 5.2.8 on 2026-01-21 19:24

from django.db import migrations, models


def migrate_non_debutee_to_en_retard(apps, schema_editor):
    """
    Migre les tâches avec statut NON_DEBUTEE vers EN_RETARD.
    """
    Tache = apps.get_model('api_planification', 'Tache')
    updated = Tache.objects.filter(statut='NON_DEBUTEE').update(statut='EN_RETARD')
    if updated > 0:
        print(f"  Migrated {updated} task(s) from NON_DEBUTEE to EN_RETARD")


def reverse_migration(apps, schema_editor):
    """
    Reverse: EN_RETARD -> NON_DEBUTEE
    """
    Tache = apps.get_model('api_planification', 'Tache')
    Tache.objects.filter(statut='EN_RETARD').update(statut='NON_DEBUTEE')


class Migration(migrations.Migration):

    dependencies = [
        ('api_planification', '0009_remove_tache_id_recurrence_parent_and_more'),
    ]

    operations = [
        # 1. D'abord migrer les données existantes
        migrations.RunPython(migrate_non_debutee_to_en_retard, reverse_migration),

        # 2. Ensuite modifier le champ avec les nouveaux choix
        migrations.AlterField(
            model_name='tache',
            name='statut',
            field=models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_RETARD', 'En retard'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='PLANIFIEE', max_length=20, verbose_name='Statut'),
        ),
    ]
