# Generated by Django 5.2.8 on 2026-01-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_planification', '0010_change_statut_non_debutee_to_en_retard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='statut',
            field=models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_RETARD', 'En retard'), ('EXPIREE', 'Expirée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='PLANIFIEE', max_length=20, verbose_name='Statut'),
        ),
    ]
