# Generated by Django 5.2.8 on 2026-01-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_planification', '0011_add_expiree_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création'),
        ),
    ]
