# Generated by Django 5.2.8 on 2026-01-22 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_planification', '0012_add_date_creation_to_tache'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='temps_travail_manuel',
            field=models.FloatField(blank=True, help_text='Temps de travail saisi manuellement (écrase le calcul automatique)', null=True, verbose_name='Temps de travail manuel (heures)'),
        ),
        migrations.AddField(
            model_name='tache',
            name='temps_travail_manuel_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de saisie manuelle'),
        ),
        migrations.AddField(
            model_name='tache',
            name='temps_travail_manuel_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_temps_manuel', to=settings.AUTH_USER_MODEL, verbose_name='Temps manuel saisi par'),
        ),
    ]
