# Generated by Django 5.2.8 on 2026-01-22 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_planification', '0013_add_temps_travail_manuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributioncharge',
            name='date_completion',
            field=models.DateTimeField(blank=True, help_text='Horodatage quand la distribution passe REALISEE', null=True, verbose_name='Date/heure de complétion'),
        ),
        migrations.AddField(
            model_name='distributioncharge',
            name='date_demarrage',
            field=models.DateTimeField(blank=True, help_text='Horodatage quand la distribution passe EN_COURS', null=True, verbose_name='Date/heure de démarrage'),
        ),
        migrations.AddField(
            model_name='distributioncharge',
            name='distribution_origine',
            field=models.ForeignKey(blank=True, help_text='Distribution dont celle-ci est le report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributions_reportees', to='api_planification.distributioncharge', verbose_name="Distribution d'origine"),
        ),
        migrations.AddField(
            model_name='distributioncharge',
            name='distribution_remplacement',
            field=models.ForeignKey(blank=True, help_text='Nouvelle distribution créée suite au report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_remplacee', to='api_planification.distributioncharge', verbose_name='Distribution de remplacement'),
        ),
        migrations.AddField(
            model_name='distributioncharge',
            name='motif_report_annulation',
            field=models.CharField(blank=True, choices=[('METEO', 'Conditions météorologiques'), ('ABSENCE', 'Absence équipe'), ('EQUIPEMENT', 'Problème équipement'), ('CLIENT', 'Demande client'), ('URGENCE', 'Réaffectation urgente'), ('AUTRE', 'Autre motif')], help_text="Raison du report ou de l'annulation", max_length=50, verbose_name='Motif de report/annulation'),
        ),
        migrations.AlterField(
            model_name='distributioncharge',
            name='status',
            field=models.CharField(choices=[('NON_REALISEE', 'Non Réalisée'), ('EN_COURS', 'En Cours'), ('REALISEE', 'Réalisée'), ('REPORTEE', 'Reportée'), ('ANNULEE', 'Annulée'), ('EN_RETARD', 'En Retard')], db_index=True, default='NON_REALISEE', help_text='État de la distribution de charge', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddIndex(
            model_name='distributioncharge',
            index=models.Index(fields=['status'], name='api_planifi_status_23e249_idx'),
        ),
        migrations.AddIndex(
            model_name='distributioncharge',
            index=models.Index(fields=['date', 'status'], name='api_planifi_date_654b0d_idx'),
        ),
    ]
