# Generated by Django 5.2.8 on 2026-01-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_planification', '0014_add_distribution_statuses_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributioncharge',
            name='heure_debut_reelle',
            field=models.TimeField(blank=True, help_text="Heure réelle de début rapportée par l'équipe", null=True, verbose_name='Heure de début réelle'),
        ),
        migrations.AddField(
            model_name='distributioncharge',
            name='heure_fin_reelle',
            field=models.TimeField(blank=True, help_text="Heure réelle de fin rapportée par l'équipe", null=True, verbose_name='Heure de fin réelle'),
        ),
    ]
