# Generated by Django 5.2.8 on 2026-01-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_planification', '0015_add_heures_reelles_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='a_ete_replanifiee',
            field=models.BooleanField(default=False, help_text='Si True, la tâche ne peut plus expirer automatiquement (statut EN_RETARD max)', verbose_name='A été replanifiée'),
        ),
    ]
