# Generated by Django 5.2.8 on 2026-01-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_planification', '0016_add_a_ete_replanifiee_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributioncharge',
            name='status',
            field=models.CharField(choices=[('NON_REALISEE', 'Non Réalisée'), ('EN_COURS', 'En Cours'), ('REALISEE', 'Réalisée'), ('REPORTEE', 'Reportée'), ('ANNULEE', 'Annulée')], db_index=True, default='NON_REALISEE', help_text='État de la distribution de charge', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='statut',
            field=models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='PLANIFIEE', max_length=20, verbose_name='Statut'),
        ),
    ]
