# Generated by Django 5.2.8 on 2026-01-27 09:44

from django.db import migrations


def cleanup_distribution_en_retard(apps, schema_editor):
    """
    Convertit toutes les distributions EN_RETARD → NON_REALISEE
    """
    DistributionCharge = apps.get_model('api_planification', 'DistributionCharge')
    
    # Compter les distributions à migrer
    en_retard_count = DistributionCharge.objects.filter(status='EN_RETARD').count()
    
    if en_retard_count > 0:
        print(f"\n{'='*60}")
        print(f"Migration: Nettoyage des distributions EN_RETARD")
        print(f"{'='*60}")
        print(f"Distributions EN_RETARD trouvées: {en_retard_count}")
        
        # Migrer EN_RETARD → NON_REALISEE
        updated = DistributionCharge.objects.filter(status='EN_RETARD').update(status='NON_REALISEE')
        
        print(f"✓ {updated} distribution(s) EN_RETARD migrée(s) vers NON_REALISEE")
        print(f"{'='*60}\n")
    else:
        print("\n✓ Aucune distribution EN_RETARD trouvée - migration ignorée\n")


class Migration(migrations.Migration):

    dependencies = [
        ('api_planification', '0017_remove_en_retard_expiree_statuts'),
    ]

    operations = [
        migrations.RunPython(
            code=cleanup_distribution_en_retard,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
