# Generated by Django 5.2.8 on 2026-01-27 09:56

from django.db import migrations


def cleanup_legacy_statuses(apps, schema_editor):
    """
    Nettoie les tâches avec des statuts legacy (EXPIREE, EN_RETARD) qui n'existent plus.
    
    Actions:
    1. Convertit EXPIREE → PLANIFIEE
    2. Convertit EN_RETARD → PLANIFIEE
    3. Restaure les distributions ANNULEE → NON_REALISEE pour ces tâches
    """
    Tache = apps.get_model('api_planification', 'Tache')
    DistributionCharge = apps.get_model('api_planification', 'DistributionCharge')
    
    # Compter les tâches à migrer
    expirees = Tache.objects.filter(statut='EXPIREE').count()
    en_retard = Tache.objects.filter(statut='EN_RETARD').count()
    
    print(f"\n{'='*60}")
    print(f"Migration: Nettoyage des statuts legacy")
    print(f"{'='*60}")
    print(f"Tâches EXPIREE trouvées: {expirees}")
    print(f"Tâches EN_RETARD trouvées: {en_retard}")
    
    # Migrer EXPIREE → PLANIFIEE
    if expirees > 0:
        taches_expirees = Tache.objects.filter(statut='EXPIREE')
        for tache in taches_expirees:
            # Restaurer les distributions annulées
            distributions_restaurees = DistributionCharge.objects.filter(
                tache=tache,
                status='ANNULEE'
            ).update(status='NON_REALISEE')
            
            # Mettre la tâche en PLANIFIEE
            tache.statut = 'PLANIFIEE'
            tache.save()
            
            if distributions_restaurees > 0:
                print(f"  ✓ Tâche #{tache.id} ({tache.reference}): EXPIREE → PLANIFIEE, {distributions_restaurees} distribution(s) restaurée(s)")
        
        print(f"✓ {expirees} tâche(s) EXPIREE migrée(s) vers PLANIFIEE")
    
    # Migrer EN_RETARD → PLANIFIEE
    if en_retard > 0:
        taches_en_retard = Tache.objects.filter(statut='EN_RETARD')
        for tache in taches_en_retard:
            # Restaurer les distributions annulées
            distributions_restaurees = DistributionCharge.objects.filter(
                tache=tache,
                status='ANNULEE'
            ).update(status='NON_REALISEE')
            
            # Mettre la tâche en PLANIFIEE
            tache.statut = 'PLANIFIEE'
            tache.save()
            
            if distributions_restaurees > 0:
                print(f"  ✓ Tâche #{tache.id} ({tache.reference}): EN_RETARD → PLANIFIEE, {distributions_restaurees} distribution(s) restaurée(s)")
        
        print(f"✓ {en_retard} tâche(s) EN_RETARD migrée(s) vers PLANIFIEE")
    
    print(f"{'='*60}")
    print(f"Migration terminée avec succès!")
    print(f"{'='*60}\n")


class Migration(migrations.Migration):

    dependencies = [
        ('api_planification', '0018_remove_en_retard_from_distributions'),
    ]

    operations = [
        migrations.RunPython(
            code=cleanup_legacy_statuses,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
