# Generated by Django 5.2.8 on 2026-01-30 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_planification', '0019_cleanup_legacy_task_statuses'),
        ('api_reclamations', '0011_reclamation_type_autre_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='a_ete_replanifiee',
            field=models.BooleanField(default=False, help_text='Flag legacy - conserve pour compatibilite avec les donnees existantes', verbose_name='A été replanifiée'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='reclamation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taches_correctives', to='api_reclamations.reclamation', verbose_name='Réclamation liée'),
        ),
    ]
