# Generated by Django 5.2.8 on 2026-02-03 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_planification', '0020_alter_tache_a_ete_replanifiee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='deleted_at',
        ),
    ]
