# Generated by Django 5.2.8 on 2026-02-05 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_planification', '0021_remove_soft_delete_from_tache'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='annulee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_annulees', to=settings.AUTH_USER_MODEL, verbose_name='Annulée par'),
        ),
        migrations.AddField(
            model_name='tache',
            name='commentaire_annulation',
            field=models.TextField(blank=True, verbose_name="Commentaire d'annulation"),
        ),
        migrations.AddField(
            model_name='tache',
            name='date_annulation',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'annulation"),
        ),
        migrations.AddField(
            model_name='tache',
            name='motif_annulation',
            field=models.CharField(blank=True, choices=[('METEO', 'Conditions météorologiques'), ('ABSENCE', 'Absence équipe'), ('EQUIPEMENT', 'Problème équipement'), ('CLIENT', 'Demande client'), ('URGENCE', 'Réaffectation urgente'), ('DOUBLON', 'Tâche en doublon'), ('ERREUR', 'Erreur de planification'), ('AUTRE', 'Autre motif')], max_length=50, null=True, verbose_name="Motif d'annulation"),
        ),
    ]
