# Generated by Django 5.2.8 on 2026-02-06 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_planification', '0022_add_task_cancellation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratioproductivite',
            name='id_type_tache',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratios_productivite', to='api_planification.typetache', verbose_name='Type de tâche'),
        ),
    ]
