# Generated by Django 5.2.8 on 2025-12-23 12:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueReclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_precedent', models.CharField(blank=True, choices=[('NOUVELLE', 'Nouvelle'), ('PRISE_EN_COMPTE', 'Prise en compte'), ('EN_COURS', 'En cours'), ('RESOLUE', 'Résolue'), ('CLOTUREE', 'Clôturée'), ('REJETEE', 'Rejetée')], max_length=20, null=True, verbose_name='Ancien statut')),
                ('statut_nouveau', models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('PRISE_EN_COMPTE', 'Prise en compte'), ('EN_COURS', 'En cours'), ('RESOLUE', 'Résolue'), ('CLOTUREE', 'Clôturée'), ('REJETEE', 'Rejetée')], max_length=20, verbose_name='Nouveau statut')),
                ('date_changement', models.DateTimeField(auto_now_add=True, verbose_name='Date du changement')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire/Message')),
            ],
            options={
                'verbose_name': 'Historique Réclamation',
                'verbose_name_plural': 'Historiques Réclamations',
                'ordering': ['-date_changement'],
            },
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reclamation', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Numéro de réclamation')),
                ('localisation', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, verbose_name='Zone affectée')),
                ('description', models.TextField(verbose_name='Description du problème')),
                ('justification_rejet', models.TextField(blank=True, null=True, verbose_name='Justification rejet/retard')),
                ('date_constatation', models.DateTimeField(verbose_name='Date de constatation')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_prise_en_compte', models.DateTimeField(blank=True, null=True, verbose_name='Date prise en compte')),
                ('date_debut_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date début traitement')),
                ('date_resolution', models.DateTimeField(blank=True, null=True, verbose_name='Date résolution')),
                ('date_cloture_prevue', models.DateTimeField(blank=True, null=True, verbose_name='Date clôture prévue')),
                ('date_cloture_reelle', models.DateTimeField(blank=True, null=True, verbose_name='Date clôture réelle')),
                ('statut', models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('PRISE_EN_COMPTE', 'Prise en compte'), ('EN_COURS', 'En cours'), ('RESOLUE', 'Résolue'), ('CLOTUREE', 'Clôturée'), ('REJETEE', 'Rejetée')], default='NOUVELLE', max_length=20, verbose_name='Statut')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Réclamation',
                'verbose_name_plural': 'Réclamations',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='SatisfactionClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Note (1-5)')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('date_evaluation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'évaluation")),
            ],
            options={
                'verbose_name': 'Satisfaction Client',
                'verbose_name_plural': 'Satisfactions Clients',
                'ordering': ['-date_evaluation'],
            },
        ),
        migrations.CreateModel(
            name='TypeReclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_reclamation', models.CharField(max_length=100, verbose_name='Nom de la réclamation')),
                ('code_reclamation', models.CharField(max_length=50, unique=True, verbose_name='Code unique')),
                ('symbole', models.CharField(blank=True, max_length=50, null=True, verbose_name='Symbole')),
                ('categorie', models.CharField(choices=[('URGENCE', 'Urgence'), ('QUALITE', 'Qualité'), ('PLANNING', 'Planning'), ('RESSOURCES', 'Ressources'), ('AUTRE', 'Autre')], max_length=50, verbose_name='Catégorie')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Type de réclamation',
                'verbose_name_plural': 'Types de réclamations',
            },
        ),
        migrations.CreateModel(
            name='Urgence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_urgence', models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYENNE', 'Moyenne'), ('HAUTE', 'Haute'), ('CRITIQUE', 'Critique')], max_length=20, verbose_name="Niveau d'urgence")),
                ('couleur', models.CharField(help_text='Code couleur HEX (ex: #FF0000)', max_length=20, verbose_name='Couleur')),
                ('delai_max_traitement', models.IntegerField(help_text='Délai maximum en heures', verbose_name='Délai max (h)')),
                ('ordre', models.IntegerField(default=1, help_text='Ordre de priorité (1-4)', verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Urgence',
                'verbose_name_plural': 'Urgences',
                'ordering': ['ordre'],
            },
        ),
    ]
