# Generated by Django 5.2.8 on 2025-12-15 16:52

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('api_users', '0003_alter_equipe_chef_equipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeReclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_reclamation', models.CharField(max_length=100, verbose_name='Nom de la réclamation')),
                ('code_reclamation', models.CharField(max_length=50, unique=True, verbose_name='Code unique')),
                ('symbole', models.CharField(blank=True, max_length=50, null=True, verbose_name='Symbole')),
                ('categorie', models.CharField(choices=[('URGENCE', 'Urgence'), ('QUALITE', 'Qualité'), ('PLANNING', 'Planning'), ('RESSOURCES', 'Ressources'), ('AUTRE', 'Autre')], max_length=50, verbose_name='Catégorie')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Type de réclamation',
                'verbose_name_plural': 'Types de réclamations',
            },
        ),
        migrations.CreateModel(
            name='Urgence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_urgence', models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYENNE', 'Moyenne'), ('HAUTE', 'Haute'), ('CRITIQUE', 'Critique')], max_length=20, verbose_name="Niveau d'urgence")),
                ('couleur', models.CharField(help_text='Code couleur HEX (ex: #FF0000)', max_length=20, verbose_name='Couleur')),
                ('delai_max_traitement', models.IntegerField(help_text='Délai maximum en heures', verbose_name='Délai max (h)')),
                ('ordre', models.IntegerField(default=1, help_text='Ordre de priorité (1-4)', verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Urgence',
                'verbose_name_plural': 'Urgences',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reclamation', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Numéro de réclamation')),
                ('localisation', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Localisation précise')),
                ('description', models.TextField(verbose_name='Description du problème')),
                ('justification_rejet', models.TextField(blank=True, null=True, verbose_name='Justification rejet/retard')),
                ('date_constatation', models.DateTimeField(verbose_name='Date de constatation')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_prise_en_compte', models.DateTimeField(blank=True, null=True, verbose_name='Date prise en compte')),
                ('date_debut_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date début traitement')),
                ('date_resolution', models.DateTimeField(blank=True, null=True, verbose_name='Date résolution')),
                ('date_cloture_prevue', models.DateTimeField(blank=True, null=True, verbose_name='Date clôture prévue')),
                ('date_cloture_reelle', models.DateTimeField(blank=True, null=True, verbose_name='Date clôture réelle')),
                ('statut', models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('PRISE_EN_COMPTE', 'Prise en compte'), ('EN_COURS', 'En cours'), ('RESOLUE', 'Résolue'), ('CLOTUREE', 'Clôturée'), ('REJETEE', 'Rejetée')], default='NOUVELLE', max_length=20, verbose_name='Statut')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_users.client', verbose_name='Client')),
                ('equipe_affectee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_users.equipe', verbose_name='Équipe affectée')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.site', verbose_name='Site')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.soussite', verbose_name='Zone')),
                ('type_reclamation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_reclamations.typereclamation', verbose_name='Type')),
                ('urgence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_reclamations.urgence', verbose_name='Urgence')),
            ],
            options={
                'verbose_name': 'Réclamation',
                'verbose_name_plural': 'Réclamations',
                'ordering': ['-date_creation'],
            },
        ),
    ]
