# Generated by Django 5.2.8 on 2025-12-26 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_initial'),
        ('api_reclamations', '0001_initial'),
        ('api_users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquereclamation',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_users.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='createur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créateur'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='equipe_affectee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_users.equipe', verbose_name='Équipe affectée'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.site', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.soussite', verbose_name='Zone'),
        ),
        migrations.AddField(
            model_name='historiquereclamation',
            name='reclamation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='api_reclamations.reclamation', verbose_name='Réclamation'),
        ),
        migrations.AddField(
            model_name='satisfactionclient',
            name='reclamation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='satisfaction', to='api_reclamations.reclamation', verbose_name='Réclamation'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='type_reclamation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_reclamations.typereclamation', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='urgence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_reclamations.urgence', verbose_name='Urgence'),
        ),
    ]
