# Generated by Django 5.2.8 on 2025-12-15 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('api_reclamations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.site', verbose_name='Site'),
        ),
    ]
