# Generated by Django 5.2.8 on 2025-12-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_reclamations', '0002_alter_reclamation_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
    ]
