# Generated by Django 5.2.8 on 2025-12-27 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_reclamations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='cloture_proposee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clotures_proposees', to=settings.AUTH_USER_MODEL, verbose_name='Clôture proposée par'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='date_proposition_cloture',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date proposition clôture'),
        ),
        migrations.AlterField(
            model_name='historiquereclamation',
            name='statut_nouveau',
            field=models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('PRISE_EN_COMPTE', 'Prise en compte'), ('EN_COURS', 'En cours'), ('RESOLUE', 'Résolue'), ('EN_ATTENTE_VALIDATION_CLOTURE', 'En attente de validation de clôture'), ('CLOTUREE', 'Clôturée'), ('REJETEE', 'Rejetée')], max_length=50, verbose_name='Nouveau statut'),
        ),
        migrations.AlterField(
            model_name='historiquereclamation',
            name='statut_precedent',
            field=models.CharField(blank=True, choices=[('NOUVELLE', 'Nouvelle'), ('PRISE_EN_COMPTE', 'Prise en compte'), ('EN_COURS', 'En cours'), ('RESOLUE', 'Résolue'), ('EN_ATTENTE_VALIDATION_CLOTURE', 'En attente de validation de clôture'), ('CLOTUREE', 'Clôturée'), ('REJETEE', 'Rejetée')], max_length=50, null=True, verbose_name='Ancien statut'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='statut',
            field=models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('PRISE_EN_COMPTE', 'Prise en compte'), ('EN_COURS', 'En cours'), ('RESOLUE', 'Résolue'), ('EN_ATTENTE_VALIDATION_CLOTURE', 'En attente de validation de clôture'), ('CLOTUREE', 'Clôturée'), ('REJETEE', 'Rejetée')], default='NOUVELLE', max_length=50, verbose_name='Statut'),
        ),
    ]
