# Generated by Django 5.2.8 on 2025-12-16 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_reclamations', '0003_reclamation_actif'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueReclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_precedent', models.CharField(blank=True, choices=[('NOUVELLE', 'Nouvelle'), ('PRISE_EN_COMPTE', 'Prise en compte'), ('EN_COURS', 'En cours'), ('RESOLUE', 'Résolue'), ('CLOTUREE', 'Clôturée'), ('REJETEE', 'Rejetée')], max_length=20, null=True, verbose_name='Ancien statut')),
                ('statut_nouveau', models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('PRISE_EN_COMPTE', 'Prise en compte'), ('EN_COURS', 'En cours'), ('RESOLUE', 'Résolue'), ('CLOTUREE', 'Clôturée'), ('REJETEE', 'Rejetée')], max_length=20, verbose_name='Nouveau statut')),
                ('date_changement', models.DateTimeField(auto_now_add=True, verbose_name='Date du changement')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire/Message')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='api_reclamations.reclamation', verbose_name='Réclamation')),
            ],
            options={
                'verbose_name': 'Historique Réclamation',
                'verbose_name_plural': 'Historiques Réclamations',
                'ordering': ['-date_changement'],
            },
        ),
    ]
