# Generated by Django 5.2.8 on 2025-12-31 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_reclamations', '0004_alter_reclamation_date_constatation'),
        ('api_users', '0004_add_structure_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='structure_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to='api_users.structureclient', verbose_name='Structure cliente'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_legacy', to='api_users.client', verbose_name='[LEGACY] Client'),
        ),
    ]
