# Generated by Django 5.2.8 on 2025-12-16 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_reclamations', '0004_historiquereclamation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatisfactionClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Note (1-5)')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('date_evaluation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'évaluation")),
                ('reclamation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='satisfaction', to='api_reclamations.reclamation', verbose_name='Réclamation')),
            ],
            options={
                'verbose_name': 'Satisfaction Client',
                'verbose_name_plural': 'Satisfactions Clients',
                'ordering': ['-date_evaluation'],
            },
        ),
    ]
