# Generated by Django 5.2.8 on 2026-01-20 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_reclamations', '0005_add_structure_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='date_refus_intervention',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date refus intervention'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='intervention_refusee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions_refusees', to=settings.AUTH_USER_MODEL, verbose_name='Intervention refusée par'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='motif_refus_intervention',
            field=models.TextField(blank=True, null=True, verbose_name='Motif du refus (obligatoire)'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='nombre_refus',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de refus'),
        ),
        migrations.AlterField(
            model_name='historiquereclamation',
            name='statut_nouveau',
            field=models.CharField(choices=[('NOUVELLE', 'En attente de lecture'), ('PRISE_EN_COMPTE', 'Prise en compte'), ('EN_COURS', 'En attente de réalisation'), ('RESOLUE', 'Tâche terminée côté administrateur'), ('EN_ATTENTE_VALIDATION_CLOTURE', 'En attente de validation de clôture'), ('INTERVENTION_REFUSEE', 'Intervention refusée par le client'), ('CLOTUREE', 'Validée côté client'), ('REJETEE', 'Rejetée')], max_length=50, verbose_name='Nouveau statut'),
        ),
        migrations.AlterField(
            model_name='historiquereclamation',
            name='statut_precedent',
            field=models.CharField(blank=True, choices=[('NOUVELLE', 'En attente de lecture'), ('PRISE_EN_COMPTE', 'Prise en compte'), ('EN_COURS', 'En attente de réalisation'), ('RESOLUE', 'Tâche terminée côté administrateur'), ('EN_ATTENTE_VALIDATION_CLOTURE', 'En attente de validation de clôture'), ('INTERVENTION_REFUSEE', 'Intervention refusée par le client'), ('CLOTUREE', 'Validée côté client'), ('REJETEE', 'Rejetée')], max_length=50, null=True, verbose_name='Ancien statut'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='statut',
            field=models.CharField(choices=[('NOUVELLE', 'En attente de lecture'), ('PRISE_EN_COMPTE', 'Prise en compte'), ('EN_COURS', 'En attente de réalisation'), ('RESOLUE', 'Tâche terminée côté administrateur'), ('EN_ATTENTE_VALIDATION_CLOTURE', 'En attente de validation de clôture'), ('INTERVENTION_REFUSEE', 'Intervention refusée par le client'), ('CLOTUREE', 'Validée côté client'), ('REJETEE', 'Rejetée')], default='NOUVELLE', max_length=50, verbose_name='Statut'),
        ),
    ]
