# Generated by Django 5.2.8 on 2026-01-20 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_reclamations', '0006_add_intervention_refusal_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='date_rejet',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de rejet'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='rejetee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_rejetees', to=settings.AUTH_USER_MODEL, verbose_name='Rejetée par'),
        ),
    ]
