# Generated by Django 5.2.8 on 2026-01-20 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_reclamations', '0007_add_rejection_tracking_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='cloture_refusee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clotures_refusees', to=settings.AUTH_USER_MODEL, verbose_name='Clôture refusée par'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='commentaire_refus_cloture',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire refus clôture'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='date_refus_cloture',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date refus clôture'),
        ),
    ]
