# Generated by Django 5.2.8 on 2025-12-20 22:35

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_reclamations', '0007_seed_types_reclamations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='localisation',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, verbose_name='Zone affectée'),
        ),
    ]
