# Generated by Django 5.2.8 on 2026-01-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_reclamations', '0008_add_closure_refusal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='visible_client',
            field=models.BooleanField(default=True, help_text='Si décoché, la réclamation ne sera pas visible par le client (usage interne)', verbose_name='Visible par le client'),
        ),
    ]
