# Generated by Django 5.2.8 on 2026-01-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_reclamations', '0009_reclamation_visible_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquereclamation',
            name='statut_nouveau',
            field=models.CharField(choices=[('NOUVELLE', 'En attente de lecture'), ('PRISE_EN_COMPTE', 'Prise en compte'), ('EN_COURS', 'En attente de réalisation'), ('RESOLUE', 'Tâche terminée côté administrateur'), ('EN_ATTENTE_VALIDATION_CLOTURE', 'En attente de validation de clôture'), ('INTERVENTION_REFUSEE', 'Intervention refusée par le client'), ('CLOTUREE', 'Clôturée'), ('REJETEE', 'Rejetée')], max_length=50, verbose_name='Nouveau statut'),
        ),
        migrations.AlterField(
            model_name='historiquereclamation',
            name='statut_precedent',
            field=models.CharField(blank=True, choices=[('NOUVELLE', 'En attente de lecture'), ('PRISE_EN_COMPTE', 'Prise en compte'), ('EN_COURS', 'En attente de réalisation'), ('RESOLUE', 'Tâche terminée côté administrateur'), ('EN_ATTENTE_VALIDATION_CLOTURE', 'En attente de validation de clôture'), ('INTERVENTION_REFUSEE', 'Intervention refusée par le client'), ('CLOTUREE', 'Clôturée'), ('REJETEE', 'Rejetée')], max_length=50, null=True, verbose_name='Ancien statut'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='statut',
            field=models.CharField(choices=[('NOUVELLE', 'En attente de lecture'), ('PRISE_EN_COMPTE', 'Prise en compte'), ('EN_COURS', 'En attente de réalisation'), ('RESOLUE', 'Tâche terminée côté administrateur'), ('EN_ATTENTE_VALIDATION_CLOTURE', 'En attente de validation de clôture'), ('INTERVENTION_REFUSEE', 'Intervention refusée par le client'), ('CLOTUREE', 'Clôturée'), ('REJETEE', 'Rejetée')], default='NOUVELLE', max_length=50, verbose_name='Statut'),
        ),
    ]
