# Generated by Django 5.2.8 on 2026-01-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_reclamations', '0010_alter_historiquereclamation_statut_nouveau_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='type_autre_description',
            field=models.CharField(blank=True, help_text="Obligatoire si le type de réclamation est 'Autre'", max_length=255, null=True, verbose_name='Précision type (si Autre)'),
        ),
    ]
