# Generated by Django 5.2.8 on 2026-02-05 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_reclamations', '0011_reclamation_type_autre_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamation',
            name='date_cloture_prevue',
        ),
        migrations.RemoveField(
            model_name='urgence',
            name='delai_max_traitement',
        ),
    ]
