# Generated by Django 5.2.8 on 2026-02-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_reclamations', '0012_remove_delay_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='rappel_cloture_envoye',
            field=models.BooleanField(default=False, help_text='Indique si le rappel automatique (24h) a été envoyé', verbose_name='Rappel de clôture envoyé'),
        ),
    ]
