BEGIN;
--
-- Create model Utilisateur
--
CREATE TABLE "api_users_utilisateur" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "is_superuser" boolean NOT NULL, "email" varchar(254) NOT NULL UNIQUE, "nom" varchar(100) NOT NULL, "prenom" varchar(100) NOT NULL, "type_utilisateur" varchar(20) NOT NULL, "date_creation" timestamp with time zone NOT NULL, "actif" boolean NOT NULL, "derniere_connexion" timestamp with time zone NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL);
CREATE TABLE "api_users_utilisateur_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "utilisateur_id" bigint NOT NULL, "group_id" integer NOT NULL);
CREATE TABLE "api_users_utilisateur_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "utilisateur_id" bigint NOT NULL, "permission_id" integer NOT NULL);
--
-- Create model Competence
--
CREATE TABLE "api_users_competence" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "nom_competence" varchar(100) NOT NULL UNIQUE, "categorie" varchar(20) NOT NULL, "description" text NOT NULL, "ordre_affichage" integer NOT NULL CHECK ("ordre_affichage" >= 0));
--
-- Create model Equipe
--
CREATE TABLE "api_users_equipe" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "nom_equipe" varchar(100) NOT NULL, "specialite" varchar(100) NOT NULL, "actif" boolean NOT NULL, "date_creation" date NOT NULL);
--
-- Create model Role
--
CREATE TABLE "api_users_role" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "nom_role" varchar(50) NOT NULL UNIQUE, "description" text NOT NULL);
--
-- Create model Client
--
CREATE TABLE "api_users_client" ("utilisateur_id" bigint NOT NULL PRIMARY KEY, "nom_structure" varchar(255) NOT NULL, "adresse" text NOT NULL, "telephone" varchar(20) NOT NULL, "contact_principal" varchar(255) NOT NULL, "email_facturation" varchar(254) NOT NULL, "logo" varchar(200) NULL);
--
-- Create model CompetenceOperateur
--
CREATE TABLE "api_users_competenceoperateur" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "niveau" varchar(20) NOT NULL, "date_acquisition" date NULL, "date_modification" timestamp with time zone NOT NULL, "competence_id" bigint NOT NULL);
--
-- Create model Operateur
--
CREATE TABLE "api_users_operateur" ("utilisateur_id" bigint NOT NULL PRIMARY KEY, "numero_immatriculation" varchar(50) NOT NULL UNIQUE, "statut" varchar(20) NOT NULL, "date_embauche" date NOT NULL, "photo" varchar(200) NULL, "telephone" varchar(20) NOT NULL, "equipe_id" bigint NULL);
--
-- Create model HistoriqueEquipeOperateur
--
CREATE TABLE "api_users_historiqueequipeoperateur" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "date_debut" date NOT NULL, "date_fin" date NULL, "role_dans_equipe" varchar(50) NOT NULL, "equipe_id" bigint NOT NULL, "operateur_id" bigint NOT NULL);
--
-- Add field chef_equipe to equipe
--
ALTER TABLE "api_users_equipe" ADD COLUMN "chef_equipe_id" bigint NOT NULL CONSTRAINT "api_users_equipe_chef_equipe_id_17056275_fk_api_users" REFERENCES "api_users_operateur"("utilisateur_id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "api_users_equipe_chef_equipe_id_17056275_fk_api_users" IMMEDIATE;
--
-- Add field operateur to competenceoperateur
--
ALTER TABLE "api_users_competenceoperateur" ADD COLUMN "operateur_id" bigint NOT NULL CONSTRAINT "api_users_competence_operateur_id_93bdbe1c_fk_api_users" REFERENCES "api_users_operateur"("utilisateur_id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "api_users_competence_operateur_id_93bdbe1c_fk_api_users" IMMEDIATE;
--
-- Create model Absence
--
CREATE TABLE "api_users_absence" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "type_absence" varchar(20) NOT NULL, "date_debut" date NOT NULL, "date_fin" date NOT NULL, "statut" varchar(20) NOT NULL, "motif" text NOT NULL, "date_demande" timestamp with time zone NOT NULL, "date_validation" timestamp with time zone NULL, "commentaire" text NOT NULL, "validee_par_id" bigint NULL, "operateur_id" bigint NOT NULL);
--
-- Create model UtilisateurRole
--
CREATE TABLE "api_users_utilisateurrole" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "date_attribution" timestamp with time zone NOT NULL, "role_id" bigint NOT NULL, "utilisateur_id" bigint NOT NULL);
--
-- Alter unique_together for competenceoperateur (1 constraint(s))
--
ALTER TABLE "api_users_competenceoperateur" ADD CONSTRAINT "api_users_competenceoper_operateur_id_competence__37d34db8_uniq" UNIQUE ("operateur_id", "competence_id");
CREATE INDEX "api_users_utilisateur_email_066d2341_like" ON "api_users_utilisateur" ("email" varchar_pattern_ops);
ALTER TABLE "api_users_utilisateur_groups" ADD CONSTRAINT "api_users_utilisateur_gr_utilisateur_id_group_id_6d23e1d0_uniq" UNIQUE ("utilisateur_id", "group_id");
ALTER TABLE "api_users_utilisateur_groups" ADD CONSTRAINT "api_users_utilisateu_utilisateur_id_7b154287_fk_api_users" FOREIGN KEY ("utilisateur_id") REFERENCES "api_users_utilisateur" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "api_users_utilisateur_groups" ADD CONSTRAINT "api_users_utilisateur_groups_group_id_db04130b_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "api_users_utilisateur_groups_utilisateur_id_7b154287" ON "api_users_utilisateur_groups" ("utilisateur_id");
CREATE INDEX "api_users_utilisateur_groups_group_id_db04130b" ON "api_users_utilisateur_groups" ("group_id");
ALTER TABLE "api_users_utilisateur_user_permissions" ADD CONSTRAINT "api_users_utilisateur_us_utilisateur_id_permissio_62becb5c_uniq" UNIQUE ("utilisateur_id", "permission_id");
ALTER TABLE "api_users_utilisateur_user_permissions" ADD CONSTRAINT "api_users_utilisateu_utilisateur_id_dd444785_fk_api_users" FOREIGN KEY ("utilisateur_id") REFERENCES "api_users_utilisateur" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "api_users_utilisateur_user_permissions" ADD CONSTRAINT "api_users_utilisateu_permission_id_ab7c2c8a_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "api_users_utilisateur_user_permissions_utilisateur_id_dd444785" ON "api_users_utilisateur_user_permissions" ("utilisateur_id");
CREATE INDEX "api_users_utilisateur_user_permissions_permission_id_ab7c2c8a" ON "api_users_utilisateur_user_permissions" ("permission_id");
CREATE INDEX "api_users_competence_nom_competence_8ba22ed8_like" ON "api_users_competence" ("nom_competence" varchar_pattern_ops);
CREATE INDEX "api_users_role_nom_role_80ba5c4d_like" ON "api_users_role" ("nom_role" varchar_pattern_ops);
ALTER TABLE "api_users_client" ADD CONSTRAINT "api_users_client_utilisateur_id_6c17bfc2_fk_api_users" FOREIGN KEY ("utilisateur_id") REFERENCES "api_users_utilisateur" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "api_users_competenceoperateur" ADD CONSTRAINT "api_users_competence_competence_id_50aaf6ae_fk_api_users" FOREIGN KEY ("competence_id") REFERENCES "api_users_competence" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "api_users_competenceoperateur_competence_id_50aaf6ae" ON "api_users_competenceoperateur" ("competence_id");
ALTER TABLE "api_users_operateur" ADD CONSTRAINT "api_users_operateur_utilisateur_id_048a01fe_fk_api_users" FOREIGN KEY ("utilisateur_id") REFERENCES "api_users_utilisateur" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "api_users_operateur" ADD CONSTRAINT "api_users_operateur_equipe_id_cba5c9a0_fk_api_users_equipe_id" FOREIGN KEY ("equipe_id") REFERENCES "api_users_equipe" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "api_users_operateur_numero_immatriculation_4026f855_like" ON "api_users_operateur" ("numero_immatriculation" varchar_pattern_ops);
CREATE INDEX "api_users_operateur_equipe_id_cba5c9a0" ON "api_users_operateur" ("equipe_id");
ALTER TABLE "api_users_historiqueequipeoperateur" ADD CONSTRAINT "api_users_historique_equipe_id_918a621a_fk_api_users" FOREIGN KEY ("equipe_id") REFERENCES "api_users_equipe" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "api_users_historiqueequipeoperateur" ADD CONSTRAINT "api_users_historique_operateur_id_5dc80e01_fk_api_users" FOREIGN KEY ("operateur_id") REFERENCES "api_users_operateur" ("utilisateur_id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "api_users_historiqueequipeoperateur_equipe_id_918a621a" ON "api_users_historiqueequipeoperateur" ("equipe_id");
CREATE INDEX "api_users_historiqueequipeoperateur_operateur_id_5dc80e01" ON "api_users_historiqueequipeoperateur" ("operateur_id");
CREATE INDEX "api_users_equipe_chef_equipe_id_17056275" ON "api_users_equipe" ("chef_equipe_id");
CREATE INDEX "api_users_competenceoperateur_operateur_id_93bdbe1c" ON "api_users_competenceoperateur" ("operateur_id");
ALTER TABLE "api_users_absence" ADD CONSTRAINT "api_users_absence_validee_par_id_aca38ca9_fk_api_users" FOREIGN KEY ("validee_par_id") REFERENCES "api_users_utilisateur" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "api_users_absence" ADD CONSTRAINT "api_users_absence_operateur_id_06300a91_fk_api_users" FOREIGN KEY ("operateur_id") REFERENCES "api_users_operateur" ("utilisateur_id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "api_users_absence_validee_par_id_aca38ca9" ON "api_users_absence" ("validee_par_id");
CREATE INDEX "api_users_absence_operateur_id_06300a91" ON "api_users_absence" ("operateur_id");
ALTER TABLE "api_users_utilisateurrole" ADD CONSTRAINT "api_users_utilisateurrole_utilisateur_id_role_id_26561fc3_uniq" UNIQUE ("utilisateur_id", "role_id");
ALTER TABLE "api_users_utilisateurrole" ADD CONSTRAINT "api_users_utilisateurrole_role_id_e2be3671_fk_api_users_role_id" FOREIGN KEY ("role_id") REFERENCES "api_users_role" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "api_users_utilisateurrole" ADD CONSTRAINT "api_users_utilisateu_utilisateur_id_e78c2174_fk_api_users" FOREIGN KEY ("utilisateur_id") REFERENCES "api_users_utilisateur" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "api_users_utilisateurrole_role_id_e2be3671" ON "api_users_utilisateurrole" ("role_id");
CREATE INDEX "api_users_utilisateurrole_utilisateur_id_e78c2174" ON "api_users_utilisateurrole" ("utilisateur_id");
COMMIT;
