# Generated by Django 5.2.8 on 2025-12-05 16:19

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_site', models.CharField(max_length=255, verbose_name='Nom du site')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse complète')),
                ('superficie_totale', models.FloatField(blank=True, null=True, verbose_name='Surface totale m²')),
                ('code_site', models.CharField(max_length=50, unique=True, verbose_name='Code unique')),
                ('date_debut_contrat', models.DateField(blank=True, null=True)),
                ('date_fin_contrat', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True, verbose_name='Site actif')),
                ('geometrie_emprise', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Délimitation (Polygon)')),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Point central')),
            ],
        ),
        migrations.CreateModel(
            name='Arbre',
            fields=[
                ('objet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.objet')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('famille', models.CharField(blank=True, max_length=255, null=True, verbose_name='Famille')),
                ('observation', models.TextField(blank=True, null=True)),
                ('last_intervention_date', models.DateField(blank=True, null=True)),
                ('taille', models.CharField(blank=True, choices=[('Petit', 'Petit'), ('Moyen', 'Moyen'), ('Grand', 'Grand')], max_length=50, null=True)),
                ('symbole', models.CharField(blank=True, max_length=255, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            bases=('api.objet',),
        ),
        migrations.CreateModel(
            name='Arbuste',
            fields=[
                ('objet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.objet')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('famille', models.CharField(blank=True, max_length=255, null=True, verbose_name='Famille')),
                ('observation', models.TextField(blank=True, null=True)),
                ('last_intervention_date', models.DateField(blank=True, null=True)),
                ('densite', models.FloatField(blank=True, null=True)),
                ('symbole', models.CharField(blank=True, max_length=255, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            bases=('api.objet',),
        ),
        migrations.CreateModel(
            name='Aspersion',
            fields=[
                ('objet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.objet')),
                ('marque', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('diametre', models.FloatField(blank=True, null=True)),
                ('materiau', models.CharField(blank=True, max_length=100, null=True)),
                ('pression', models.FloatField(blank=True, null=True)),
                ('symbole', models.CharField(blank=True, max_length=255, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
            bases=('api.objet',),
        ),
        migrations.CreateModel(
            name='Ballon',
            fields=[
                ('objet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.objet')),
                ('marque', models.CharField(blank=True, max_length=100, null=True)),
                ('pression', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('materiau', models.CharField(blank=True, max_length=100, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            bases=('api.objet',),
        ),
        migrations.CreateModel(
            name='Cactus',
            fields=[
                ('objet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.objet')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('famille', models.CharField(blank=True, max_length=255, null=True, verbose_name='Famille')),
                ('observation', models.TextField(blank=True, null=True)),
                ('last_intervention_date', models.DateField(blank=True, null=True)),
                ('densite', models.FloatField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            bases=('api.objet',),
        ),
        migrations.CreateModel(
            name='Canalisation',
            fields=[
                ('objet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.objet')),
                ('marque', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('diametre', models.FloatField(blank=True, null=True)),
                ('materiau', models.CharField(blank=True, max_length=100, null=True)),
                ('pression', models.FloatField(blank=True, null=True)),
                ('symbole', models.CharField(blank=True, max_length=255, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
            bases=('api.objet',),
        ),
        migrations.CreateModel(
            name='Clapet',
            fields=[
                ('objet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.objet')),
                ('marque', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('diametre', models.FloatField(blank=True, null=True)),
                ('materiau', models.CharField(blank=True, max_length=100, null=True)),
                ('pression', models.FloatField(blank=True, null=True)),
                ('symbole', models.CharField(blank=True, max_length=255, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            bases=('api.objet',),
        ),
        migrations.CreateModel(
            name='Gazon',
            fields=[
                ('objet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.objet')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('famille', models.CharField(blank=True, max_length=255, null=True, verbose_name='Famille')),
                ('observation', models.TextField(blank=True, null=True)),
                ('last_intervention_date', models.DateField(blank=True, null=True)),
                ('area_sqm', models.FloatField(blank=True, null=True, verbose_name='Surface m²')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            bases=('api.objet',),
        ),
        migrations.CreateModel(
            name='Goutte',
            fields=[
                ('objet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.objet')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('diametre', models.FloatField(blank=True, null=True)),
                ('materiau', models.CharField(blank=True, max_length=100, null=True)),
                ('pression', models.FloatField(blank=True, null=True)),
                ('symbole', models.CharField(blank=True, max_length=255, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
            bases=('api.objet',),
        ),
        migrations.CreateModel(
            name='Graminee',
            fields=[
                ('objet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.objet')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('famille', models.CharField(blank=True, max_length=255, null=True, verbose_name='Famille')),
                ('observation', models.TextField(blank=True, null=True)),
                ('last_intervention_date', models.DateField(blank=True, null=True)),
                ('densite', models.FloatField(blank=True, null=True)),
                ('symbole', models.CharField(blank=True, max_length=255, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            bases=('api.objet',),
        ),
        migrations.CreateModel(
            name='Palmier',
            fields=[
                ('objet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.objet')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('famille', models.CharField(blank=True, max_length=255, null=True, verbose_name='Famille')),
                ('observation', models.TextField(blank=True, null=True)),
                ('last_intervention_date', models.DateField(blank=True, null=True)),
                ('taille', models.CharField(blank=True, choices=[('Petit', 'Petit'), ('Moyen', 'Moyen'), ('Grand', 'Grand')], max_length=50, null=True)),
                ('symbole', models.CharField(blank=True, max_length=255, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            bases=('api.objet',),
        ),
        migrations.CreateModel(
            name='Pompe',
            fields=[
                ('objet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.objet')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('observation', models.TextField(blank=True, null=True)),
                ('last_intervention_date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('diametre', models.FloatField(blank=True, null=True)),
                ('puissance', models.FloatField(blank=True, null=True)),
                ('debit', models.FloatField(blank=True, null=True)),
                ('symbole', models.CharField(blank=True, max_length=255, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            bases=('api.objet',),
        ),
        migrations.CreateModel(
            name='Puit',
            fields=[
                ('objet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.objet')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('observation', models.TextField(blank=True, null=True)),
                ('last_intervention_date', models.DateField(blank=True, null=True)),
                ('profondeur', models.FloatField(blank=True, null=True)),
                ('diametre', models.FloatField(blank=True, null=True)),
                ('niveau_statique', models.FloatField(blank=True, null=True)),
                ('niveau_dynamique', models.FloatField(blank=True, null=True)),
                ('symbole', models.CharField(blank=True, max_length=255, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            bases=('api.objet',),
        ),
        migrations.CreateModel(
            name='Vanne',
            fields=[
                ('objet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.objet')),
                ('marque', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('diametre', models.FloatField(blank=True, null=True)),
                ('materiau', models.CharField(blank=True, max_length=100, null=True)),
                ('pression', models.FloatField(blank=True, null=True)),
                ('symbole', models.CharField(blank=True, max_length=255, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            bases=('api.objet',),
        ),
        migrations.CreateModel(
            name='Vivace',
            fields=[
                ('objet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.objet')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('famille', models.CharField(blank=True, max_length=255, null=True, verbose_name='Famille')),
                ('observation', models.TextField(blank=True, null=True)),
                ('last_intervention_date', models.DateField(blank=True, null=True)),
                ('densite', models.FloatField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            bases=('api.objet',),
        ),
        migrations.AddField(
            model_name='objet',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.site'),
        ),
        migrations.CreateModel(
            name='SousSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Unit', max_length=255, verbose_name='Nom de la villa/unité')),
                ('geometrie', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Localisation')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_sites', to='api.site')),
            ],
        ),
        migrations.AddField(
            model_name='objet',
            name='sous_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.soussite'),
        ),
    ]
