# Generated by Django 5.2.8 on 2025-12-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objet',
            name='etat',
            field=models.CharField(choices=[('bon', 'Bon état'), ('moyen', 'État moyen'), ('mauvais', 'Mauvais état'), ('critique', 'État critique')], default='bon', max_length=20, verbose_name="État de l'objet"),
        ),
    ]
