# Generated by Django 5.2.8 on 2025-12-23 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('api_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='api_users.client', verbose_name='Client propriétaire'),
        ),
        migrations.AddField(
            model_name='objet',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.site'),
        ),
        migrations.AddField(
            model_name='soussite',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_sites', to='api.site'),
        ),
        migrations.AddField(
            model_name='objet',
            name='sous_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.soussite'),
        ),
    ]
