# Generated by Django 5.2.8 on 2025-12-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='code_site',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Code unique'),
        ),
    ]
