# Generated by Django 5.2.8 on 2025-12-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_site_code_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='objet',
            name='etat',
            field=models.CharField(choices=[('bon', 'Bon'), ('moyen', 'Moyen'), ('mauvais', 'Mauvais')], default='bon', max_length=50, verbose_name='État'),
        ),
    ]
