# Generated by Django 5.2.8 on 2025-12-27 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
        ('api_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='superviseur',
            field=models.ForeignKey(blank=True, help_text='Superviseur responsable de la gestion de ce site', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites_affectes', to='api_users.superviseur', verbose_name='Superviseur affecté'),
        ),
    ]
