# Generated by Django 5.2.8 on 2025-12-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_objet_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbre',
            name='famille',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Famille'),
        ),
        migrations.AlterField(
            model_name='arbre',
            name='last_intervention_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='arbre',
            name='taille',
            field=models.CharField(blank=True, choices=[('Petit', 'Petit'), ('Moyen', 'Moyen'), ('Grand', 'Grand')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gazon',
            name='area_sqm',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Surface m²'),
        ),
        migrations.AlterField(
            model_name='gazon',
            name='famille',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Famille'),
        ),
        migrations.AlterField(
            model_name='gazon',
            name='last_intervention_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='objet',
            name='etat',
            field=models.CharField(choices=[('bon', 'Bon état'), ('moyen', 'État moyen'), ('mauvais', 'Mauvais état'), ('critique', 'État critique')], db_index=True, default='bon', max_length=20, verbose_name="État de l'objet"),
        ),
        migrations.AlterField(
            model_name='palmier',
            name='famille',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Famille'),
        ),
        migrations.AlterField(
            model_name='palmier',
            name='last_intervention_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='palmier',
            name='taille',
            field=models.CharField(blank=True, choices=[('Petit', 'Petit'), ('Moyen', 'Moyen'), ('Grand', 'Grand')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='puit',
            name='diametre',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='puit',
            name='last_intervention_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='puit',
            name='profondeur',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
