# Generated by Django 5.2.8 on 2025-12-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_objet_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspersion',
            name='nom',
            field=models.CharField(default='Sans nom', max_length=255, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='ballon',
            name='nom',
            field=models.CharField(default='Sans nom', max_length=255, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='canalisation',
            name='nom',
            field=models.CharField(default='Sans nom', max_length=255, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='clapet',
            name='nom',
            field=models.CharField(default='Sans nom', max_length=255, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='goutte',
            name='nom',
            field=models.CharField(default='Sans nom', max_length=255, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='vanne',
            name='nom',
            field=models.CharField(default='Sans nom', max_length=255, verbose_name='Nom'),
        ),
    ]
