# Generated by Django 5.2.8 on 2025-12-31 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_superviseur_to_site'),
        ('api_users', '0004_add_structure_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='structure_client',
            field=models.ForeignKey(blank=True, help_text='Structure/organisation propriétaire du site', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='api_users.structureclient', verbose_name='Structure cliente'),
        ),
        migrations.AlterField(
            model_name='site',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sites_legacy', to='api_users.client', verbose_name='[LEGACY] Client propriétaire'),
        ),
    ]
