# Generated by Django 5.2.8 on 2026-01-01 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_structure_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('tache_creee', 'Nouvelle tache'), ('tache_assignee', 'Tache assignee'), ('tache_modifiee', 'Tache modifiee'), ('tache_terminee', 'Tache terminee'), ('tache_en_retard', 'Tache en retard'), ('tache_annulee', 'Tache annulee'), ('reclamation_creee', 'Nouvelle reclamation'), ('reclamation_urgente', 'Reclamation urgente'), ('reclamation_prise_en_compte', 'Reclamation prise en compte'), ('reclamation_resolue', 'Reclamation resolue'), ('reclamation_cloturee', 'Reclamation cloturee'), ('absence_demandee', 'Demande absence'), ('absence_validee', 'Absence validee'), ('absence_refusee', 'Absence refusee'), ('equipe_membre_ajoute', 'Membre ajoute'), ('equipe_membre_retire', 'Membre retire'), ('info', 'Information'), ('alerte', 'Alerte')], default='info', max_length=50, verbose_name='Type')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('priorite', models.CharField(choices=[('low', 'Basse'), ('normal', 'Normale'), ('high', 'Haute'), ('urgent', 'Urgente')], default='normal', max_length=10, verbose_name='Priorite')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Donnees supplementaires (IDs, liens, etc.)', verbose_name='Donnees JSON')),
                ('lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('acteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_envoyees', to=settings.AUTH_USER_MODEL, verbose_name='Acteur')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['destinataire', 'lu', '-created_at'], name='api_notific_destina_781193_idx'), models.Index(fields=['type_notification'], name='api_notific_type_no_10ff60_idx')],
            },
        ),
    ]
