# Generated by Django 5.2.8 on 2026-01-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_notification_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('tache_creee', 'Nouvelle tache'), ('tache_assignee', 'Tache assignee'), ('tache_modifiee', 'Tache modifiee'), ('tache_terminee', 'Tache terminee'), ('tache_en_retard', 'Tache en retard'), ('tache_annulee', 'Tache annulee'), ('reclamation_creee', 'Nouvelle reclamation'), ('reclamation_urgente', 'Reclamation urgente'), ('reclamation_prise_en_compte', 'Reclamation prise en compte'), ('reclamation_resolue', 'Reclamation resolue'), ('reclamation_cloturee', 'Reclamation cloturee'), ('absence_demandee', 'Demande absence'), ('absence_validee', 'Absence validee'), ('absence_refusee', 'Absence refusee'), ('equipe_membre_ajoute', 'Membre ajoute'), ('equipe_membre_retire', 'Membre retire'), ('site_assigne', 'Site assigne'), ('site_retire', 'Site retire'), ('site_cree', 'Nouveau site'), ('site_modifie', 'Site modifie'), ('info', 'Information'), ('alerte', 'Alerte')], default='info', max_length=50, verbose_name='Type'),
        ),
    ]
