# Generated by Django 5.2.8 on 2025-12-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_nom_from_hydraulic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objet',
            name='etat',
            field=models.CharField(choices=[('bon', 'Bon'), ('moyen', 'Moyen'), ('mauvais', 'Mauvais'), ('critique', 'Critique')], default='bon', max_length=50, verbose_name='État'),
        ),
    ]
