# Generated by Django 5.2.8 on 2025-12-18 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_objet_etat'),
        ('api_users', '0004_remove_equipe_specialite'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='api_users.client', verbose_name='Client propriétaire'),
        ),
    ]
