# Generated by Django 5.2.8 on 2025-12-19 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_arbre_famille_and_more'),
        ('api', '0007_site_client'),
    ]

    operations = [
    ]
