# Generated by Django 5.2.8 on 2025-12-23 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('api_planification', '0001_initial'),
        ('api_reclamations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(help_text='Nom commercial du produit', max_length=255, verbose_name='Nom commercial')),
                ('numero_homologation', models.CharField(blank=True, help_text="Numéro d'homologation officiel", max_length=100, verbose_name="Numéro d'homologation")),
                ('date_validite', models.DateField(blank=True, help_text='Date limite de validité/homologation', null=True, verbose_name='Date de validité')),
                ('cible', models.CharField(blank=True, help_text='Exemple: Ver du gazon, mauvaises herbes', max_length=255, verbose_name='Cible')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, help_text='Désactiver si produit retiré du marché', verbose_name='Produit actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['nom_produit'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.ImageField(blank=True, help_text='Fichier image uploadé', max_length=500, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Fichier Photo')),
                ('type_photo', models.CharField(choices=[('AVANT', 'Avant intervention'), ('APRES', 'Après intervention'), ('RECLAMATION', 'Réclamation'), ('INVENTAIRE', 'Inventaire')], max_length=20, verbose_name='Type de photo')),
                ('date_prise', models.DateTimeField(auto_now_add=True, help_text='Date et heure de la prise de photo', verbose_name='Date de prise')),
                ('legende', models.CharField(blank=True, help_text='Description de la photo', max_length=255, verbose_name='Légende')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('objet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.objet', verbose_name='Objet inventaire')),
                ('reclamation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api_reclamations.reclamation', verbose_name='Réclamation')),
                ('tache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api_planification.tache', verbose_name='Tâche')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['-date_prise'],
            },
        ),
        migrations.CreateModel(
            name='DoseProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_valeur', models.DecimalField(decimal_places=2, help_text='Valeur numérique de la dose', max_digits=10, verbose_name='Dose (valeur)')),
                ('dose_unite_produit', models.CharField(help_text='cc, g, kg, ml, l...', max_length=20, verbose_name='Unité produit')),
                ('dose_unite_support', models.CharField(help_text='hl, ha, m²...', max_length=20, verbose_name='Unité support')),
                ('contexte', models.CharField(blank=True, help_text='Précision sur le contexte (ex: gazon, arbustes)', max_length=255, verbose_name="Contexte d'utilisation")),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='api_suivi_taches.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Dose produit',
                'verbose_name_plural': 'Doses produits',
                'ordering': ['produit'],
            },
        ),
        migrations.CreateModel(
            name='ConsommationProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_utilisee', models.DecimalField(decimal_places=2, help_text='Quantité réellement consommée', max_digits=10, verbose_name='Quantité utilisée')),
                ('unite', models.CharField(help_text='cc, g, kg, ml, l...', max_length=20, verbose_name='Unité de mesure')),
                ('date_utilisation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'utilisation")),
                ('commentaire', models.TextField(blank=True, help_text="Observations sur l'utilisation", verbose_name='Commentaire')),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consommations_produits', to='api_planification.tache', verbose_name='Tâche')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consommations', to='api_suivi_taches.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Consommation produit',
                'verbose_name_plural': 'Consommations produits',
                'ordering': ['tache', 'date_utilisation'],
                'unique_together': {('tache', 'produit')},
            },
        ),
        migrations.CreateModel(
            name='ProduitMatiereActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere_active', models.CharField(help_text='Nom de la matière active', max_length=255, verbose_name='Matière active')),
                ('teneur_valeur', models.DecimalField(decimal_places=2, help_text='Valeur numérique de la teneur', max_digits=10, verbose_name='Teneur (valeur)')),
                ('teneur_unite', models.CharField(default='%', help_text='%, g/l, fraction...', max_length=20, verbose_name='Teneur (unité)')),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage si plusieurs matières actives", verbose_name="Ordre d'affichage")),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres_actives', to='api_suivi_taches.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Matière active',
                'verbose_name_plural': 'Matières actives',
                'ordering': ['produit', 'ordre', 'matiere_active'],
                'unique_together': {('produit', 'matiere_active')},
            },
        ),
    ]
