# Generated by Django 5.2.8 on 2025-12-15 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_reclamations', '0001_initial'),
        ('api_suivi_taches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='reclamation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api_reclamations.reclamation', verbose_name='Réclamation'),
        ),
    ]
