# Generated by Django 5.2.8 on 2026-01-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_suivi_taches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilisant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Engrais NPK, Compost, Biostimulant', max_length=255, verbose_name='Nom du fertilisant')),
                ('type_fertilisant', models.CharField(choices=[('CHIMIQUE', 'Chimique'), ('ORGANIQUE', 'Organique'), ('BIOLOGIQUE', 'Biologique'), ('MINERAL', 'Amendement minéral'), ('SUBSTRAT', 'Substrat organique')], help_text='Catégorie du fertilisant', max_length=20, verbose_name='Type')),
                ('format_fertilisant', models.CharField(choices=[('GRANULE', 'Granulé'), ('LIQUIDE', 'Liquide'), ('POUDRE', 'Poudre'), ('SOLIDE', 'Solide'), ('DECOMPOSE', 'Décomposé')], help_text='Forme physique du produit', max_length=20, verbose_name='Format')),
                ('description', models.TextField(blank=True, help_text='Informations complémentaires sur le fertilisant', verbose_name='Description')),
                ('actif', models.BooleanField(default=True, help_text='Désactiver si produit non disponible', verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Fertilisant',
                'verbose_name_plural': 'Fertilisants',
                'ordering': ['nom', 'type_fertilisant'],
            },
        ),
        migrations.CreateModel(
            name='RavageurMaladie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Cochenilles, Mildiou, Pucerons', max_length=255, verbose_name='Nom')),
                ('categorie', models.CharField(choices=[('RAVAGEUR', 'Ravageur'), ('MALADIE', 'Maladie')], help_text='Ravageur (insecte) ou Maladie (fongique/bactérienne)', max_length=20, verbose_name='Catégorie')),
                ('symptomes', models.TextField(help_text="Description des signes visibles de l'infestation/infection", verbose_name='Symptômes')),
                ('partie_atteinte', models.CharField(help_text='Ex: Feuilles, Tiges, Racines, Écorce, Fruits', max_length=255, verbose_name='Partie atteinte')),
                ('actif', models.BooleanField(default=True, help_text='Désactiver si entrée obsolète', verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('produits_recommandes', models.ManyToManyField(blank=True, help_text='Produits phytosanitaires efficaces contre ce ravageur/maladie', related_name='ravageurs_maladies', to='api_suivi_taches.produit', verbose_name='Produits recommandés')),
            ],
            options={
                'verbose_name': 'Ravageur / Maladie',
                'verbose_name_plural': 'Ravageurs et Maladies',
                'ordering': ['categorie', 'nom'],
            },
        ),
    ]
