# Generated by Django 5.2.8 on 2025-12-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_suivi_taches', '0002_photo_reclamation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='url_fichier',
        ),
        migrations.AddField(
            model_name='photo',
            name='fichier',
            field=models.ImageField(blank=True, help_text='Fichier image uploadé', max_length=500, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Fichier Photo'),
        ),
    ]
