# Generated by Django 5.2.8 on 2025-12-26 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='Adresse email de connexion (unique)', max_length=254, unique=True, verbose_name='Email')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('actif', models.BooleanField(default=True, help_text='Désactiver plutôt que supprimer (soft delete)', verbose_name='Actif')),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_competence', models.CharField(max_length=100, unique=True, verbose_name='Nom de la compétence')),
                ('categorie', models.CharField(choices=[('TECHNIQUE', 'Techniques et opérationnelles'), ('ORGANISATIONNELLE', 'Organisationnelles et humaines')], max_length=20, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ordre_affichage', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['categorie', 'ordre_affichage', 'nom_competence'],
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_equipe', models.CharField(max_length=100, verbose_name="Nom de l'équipe")),
                ('actif', models.BooleanField(default=True, verbose_name='Équipe active')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Équipe',
                'verbose_name_plural': 'Équipes',
                'ordering': ['nom_equipe'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('SUPERVISEUR', 'Superviseur'), ('CLIENT', 'Client')], max_length=50, unique=True, verbose_name='Nom du rôle')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='client_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nom_structure', models.CharField(help_text="Nom de l'entreprise ou organisation", max_length=255, verbose_name='Nom de la structure')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse complète')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('contact_principal', models.CharField(blank=True, max_length=255, verbose_name='Contact principal')),
                ('email_facturation', models.EmailField(blank=True, max_length=254, verbose_name='Email de facturation')),
                ('logo', models.URLField(blank=True, help_text="URL du logo de l'organisation", null=True, verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Superviseur',
            fields=[
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='superviseur_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('matricule', models.CharField(max_length=50, unique=True, verbose_name='Matricule superviseur')),
                ('secteur_geographique', models.CharField(blank=True, help_text='Zone géographique sous sa responsabilité', max_length=255, verbose_name='Secteur géographique')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone professionnel')),
                ('date_prise_fonction', models.DateField(verbose_name='Date de prise de fonction')),
            ],
            options={
                'verbose_name': 'Superviseur',
                'verbose_name_plural': 'Superviseurs',
                'ordering': ['utilisateur__nom', 'utilisateur__prenom'],
            },
        ),
        migrations.CreateModel(
            name='CompetenceOperateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('NON', 'Non maîtrisé'), ('DEBUTANT', 'Débutant'), ('INTERMEDIAIRE', 'Intermédiaire'), ('EXPERT', 'Expert')], default='NON', max_length=20, verbose_name='Niveau de maîtrise')),
                ('date_acquisition', models.DateField(blank=True, null=True, verbose_name="Date d'acquisition")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operateurs_competence', to='api_users.competence')),
            ],
            options={
                'verbose_name': 'Compétence opérateur',
                'verbose_name_plural': 'Compétences opérateurs',
            },
        ),
        migrations.CreateModel(
            name='Operateur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(blank=True, help_text="Pour communication interne uniquement (n'est PAS un compte de connexion)", max_length=254, verbose_name='Email professionnel')),
                ('numero_immatriculation', models.CharField(help_text="Numéro d'immatriculation unique", max_length=50, unique=True, verbose_name='Matricule')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('EN_CONGE', 'En congé')], default='ACTIF', max_length=20, verbose_name='Statut')),
                ('date_embauche', models.DateField(verbose_name="Date d'embauche")),
                ('date_sortie', models.DateField(blank=True, help_text='Date de fin de contrat ou départ', null=True, verbose_name='Date de sortie')),
                ('photo', models.URLField(blank=True, help_text="URL de la photo de l'opérateur", null=True, verbose_name='Photo')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('competences', models.ManyToManyField(related_name='operateurs', through='api_users.CompetenceOperateur', to='api_users.competence', verbose_name='Compétences')),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operateurs', to='api_users.equipe', verbose_name='Équipe')),
                ('superviseur', models.ForeignKey(blank=True, help_text='Superviseur qui gère cet opérateur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operateurs_supervises', to='api_users.superviseur', verbose_name='Superviseur responsable')),
            ],
            options={
                'verbose_name': 'Opérateur',
                'verbose_name_plural': 'Opérateurs',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueEquipeOperateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name="Date d'entrée dans l'équipe")),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name="Date de sortie de l'équipe")),
                ('role_dans_equipe', models.CharField(default='MEMBRE', max_length=50, verbose_name="Rôle dans l'équipe")),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_operateurs', to='api_users.equipe')),
                ('operateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_equipes', to='api_users.operateur')),
            ],
            options={
                'verbose_name': 'Historique équipe',
                'verbose_name_plural': 'Historiques équipes',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.AddField(
            model_name='equipe',
            name='chef_equipe',
            field=models.OneToOneField(blank=True, help_text="Opérateur désigné comme chef (doit avoir compétence 'Gestion d\\'équipe')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipe_dirigee', to='api_users.operateur', verbose_name="Chef d'équipe"),
        ),
        migrations.AddField(
            model_name='competenceoperateur',
            name='operateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences_operateur', to='api_users.operateur'),
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_absence', models.CharField(choices=[('CONGE', 'Congé'), ('MALADIE', 'Maladie'), ('FORMATION', 'Formation'), ('AUTRE', 'Autre')], max_length=20, verbose_name="Type d'absence")),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('statut', models.CharField(choices=[('DEMANDEE', 'Demandée'), ('VALIDEE', 'Validée'), ('REFUSEE', 'Refusée'), ('ANNULEE', 'Annulée')], default='DEMANDEE', max_length=20, verbose_name='Statut')),
                ('motif', models.TextField(blank=True, verbose_name='Motif')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de demande')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validée par')),
                ('operateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='api_users.operateur', verbose_name='Opérateur')),
            ],
            options={
                'verbose_name': 'Absence',
                'verbose_name_plural': 'Absences',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.AddField(
            model_name='equipe',
            name='superviseur',
            field=models.ForeignKey(blank=True, help_text='Superviseur qui gère cette équipe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_gerees', to='api_users.superviseur', verbose_name='Superviseur responsable'),
        ),
        migrations.AlterUniqueTogether(
            name='competenceoperateur',
            unique_together={('operateur', 'competence')},
        ),
        migrations.CreateModel(
            name='UtilisateurRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attribution', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs_role', to='api_users.role')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_utilisateur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attribution de rôle',
                'verbose_name_plural': 'Attributions de rôles',
                'unique_together': {('utilisateur', 'role')},
            },
        ),
    ]
