# Generated by Django 5.2.8 on 2025-12-27 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_superviseur_to_site'),
        ('api_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='site',
            field=models.ForeignKey(blank=True, help_text="Site auquel l'équipe est affectée de manière contractuelle (affectation de base)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_affectees', to='api.site', verbose_name="Site d'affectation contractuelle"),
        ),
    ]
