# Generated by Django 5.2.8 on 2025-12-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competenceoperateur',
            name='niveau',
            field=models.CharField(choices=[('NON', 'Non maîtrisé'), ('DEBUTANT', 'Débutant'), ('INTERMEDIAIRE', 'Intermédiaire'), ('EXPERT', 'Expert')], default='NON', max_length=20, verbose_name='Niveau de maîtrise'),
        ),
    ]
