# Generated by Django 5.2.8 on 2025-12-27 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0002_equipe_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='superviseur',
        ),
    ]
