# Generated by Django 5.2.8 on 2025-12-13 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0002_alter_competenceoperateur_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='chef_equipe',
            field=models.ForeignKey(blank=True, help_text="Doit avoir la compétence 'Gestion d'equipe' (optionnel)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_dirigees', to='api_users.operateur', verbose_name="Chef d'équipe"),
        ),
    ]
