# Generated by Django 5.2.8 on 2025-12-31 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0003_remove_equipe_superviseur'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom de l'entreprise ou organisation", max_length=255, verbose_name='Nom de la structure')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse complète')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('contact_principal', models.CharField(blank=True, max_length=255, verbose_name='Contact principal')),
                ('email_facturation', models.EmailField(blank=True, max_length=254, verbose_name='Email de facturation')),
                ('logo', models.URLField(blank=True, help_text="URL du logo de l'organisation", null=True, verbose_name='Logo')),
                ('actif', models.BooleanField(default=True, verbose_name='Structure active')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Structure Client',
                'verbose_name_plural': 'Structures Clients',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='nom_structure',
            field=models.CharField(blank=True, default='', help_text='[LEGACY] Sera migré vers StructureClient.nom', max_length=255, verbose_name='Nom de la structure'),
        ),
        migrations.AddField(
            model_name='client',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs', to='api_users.structureclient', verbose_name='Structure'),
        ),
    ]
