# Generated by Django 5.2.8 on 2025-12-17 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0003_alter_equipe_chef_equipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='specialite',
        ),
    ]
