# Generated by Django 5.2.8 on 2026-01-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0005_migrate_clients_to_structures'),
    ]

    operations = [
        migrations.AddField(
            model_name='structureclient',
            name='logo_url',
            field=models.CharField(blank=True, help_text='URL externe du logo (utilisé si pas de fichier uploadé)', max_length=500, null=True, verbose_name='Logo (URL)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.CharField(blank=True, help_text="URL du logo de l'organisation (accepte tous formats d'URL)", max_length=500, null=True, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='structureclient',
            name='logo',
            field=models.ImageField(blank=True, help_text='Fichier image du logo', null=True, upload_to='structures/logos/', verbose_name='Logo (fichier)'),
        ),
    ]
