# Generated by Django 5.2.8 on 2026-01-06 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_notification_type_notification'),
        ('api_users', '0006_structureclient_logo_url_alter_client_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='site_principal',
            field=models.ForeignKey(blank=True, help_text="Site d'affectation contractuelle de base (détermine le superviseur)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_principales', to='api.site', verbose_name='Site principal'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='sites_secondaires',
            field=models.ManyToManyField(blank=True, help_text="Sites proches géographiquement où l'équipe peut aussi intervenir", related_name='equipes_secondaires', to='api.site', verbose_name='Sites secondaires'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='site',
            field=models.ForeignKey(blank=True, help_text='[LEGACY] Sera migré vers site_principal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_affectees_legacy', to='api.site', verbose_name='[LEGACY] Site'),
        ),
    ]
