# Generated by Django 5.2.8 on 2026-01-08 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0007_equipe_site_principal_equipe_sites_secondaires_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraireTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.CharField(choices=[('LUN', 'Lundi'), ('MAR', 'Mardi'), ('MER', 'Mercredi'), ('JEU', 'Jeudi'), ('VEN', 'Vendredi'), ('SAM', 'Samedi'), ('DIM', 'Dimanche')], max_length=3, verbose_name='Jour de la semaine')),
                ('heure_debut', models.TimeField(help_text='Exemple: 08:00', verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(help_text='Exemple: 17:00', verbose_name='Heure de fin')),
                ('duree_pause_minutes', models.PositiveIntegerField(default=60, help_text='Durée de la pause déjeuner (par défaut 60 min)', verbose_name='Pause déjeuner (minutes)')),
                ('actif', models.BooleanField(default=True, help_text='Horaire actif (décocher pour jours fériés exceptionnels)', verbose_name='Actif')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='api_users.equipe', verbose_name='Équipe')),
            ],
            options={
                'verbose_name': 'Horaire de travail',
                'verbose_name_plural': 'Horaires de travail',
                'ordering': ['equipe', 'jour_semaine'],
                'unique_together': {('equipe', 'jour_semaine')},
            },
        ),
    ]
