# Generated by Django 5.2.8 on 2026-01-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0008_add_horaire_travail'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourFerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du jour férié')),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('type_ferie', models.CharField(choices=[('NATIONAL', 'Férié national'), ('LOCAL', 'Férié local'), ('RELIGIEUX', 'Férié religieux'), ('AUTRE', 'Autre')], default='NATIONAL', max_length=20, verbose_name='Type de férié')),
                ('recurrent', models.BooleanField(default=False, help_text='Si coché, ce jour férié se répète chaque année (ex: Fête du Travail)', verbose_name='Récurrent annuellement')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, help_text='Décocher pour désactiver temporairement un jour férié', verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Jour férié',
                'verbose_name_plural': 'Jours fériés',
                'db_table': 'api_users_jour_ferie',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date', 'actif'], name='api_users_j_date_2c3dae_idx')],
                'unique_together': {('date', 'type_ferie')},
            },
        ),
    ]
