# Generated by Django 5.2.8 on 2026-01-11 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0009_jourferie'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horairetravail',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='horairetravail',
            name='equipe',
            field=models.ForeignKey(blank=True, help_text='Laisser vide pour une configuration globale (par défaut)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='api_users.equipe', verbose_name='Équipe'),
        ),
        migrations.AddConstraint(
            model_name='horairetravail',
            constraint=models.UniqueConstraint(condition=models.Q(('equipe__isnull', False)), fields=('equipe', 'jour_semaine'), name='unique_equipe_jour'),
        ),
        migrations.AddConstraint(
            model_name='horairetravail',
            constraint=models.UniqueConstraint(condition=models.Q(('equipe__isnull', True)), fields=('jour_semaine',), name='unique_global_jour'),
        ),
    ]
